os: linux
dist: trusty

language: node_js
node_js: 12

cache:
  yarn: true

script:
  - yarn lint
  - yarn build
  - yarn test:coverage

after_script:
  - bash <(wget -q -O - https://coverage.codacy.com/get.sh)

deploy:
  skip_cleanup: true
  provider: script
  script: yarn semantic-release

